### ISSUE TITLE
zero log scores

### ISSUE THREAD

**Issue by elray1** [FluSightNetwork/cdc-flusight-ensemble#21]
Log scores of 0 in the summary statistics table are probably wrong, e.g. for CU-BMA and ReichLab-SARIMA1 in HHS Region 3 in 2012/2013.

**Comment by lepisma** [comment]
I looked into the issue. There are some predictions which have distributions so that the actual value lies in a bin with `0` probability resulting in `-Infinity` after `Math.log`. This then infects all the other values (while taking mean) for a model and target. How should this be handled? Maybe by taking a lower limit of `epsilon` instead of 0?

PS: the `0` is because `-Infinity` gets written as `null` in JS and then gets picked up as `0` (this can be changed to show something else),

**Comment by nickreich** [comment]
I think it'd be better to have these scores shown as "NA". The models 
themselves should have an epsilon-hedge. And if they don't they should 
be penalized for it, IMHO.

**Comment by lepisma** [comment]
Made those values show up as `NA` now.
