### ISSUE TITLE
need reproducible load of epiforecast package in forecast validation script

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#22]
https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/891cb0382586892bfc5f41950ad3f12e6b0da511/scripts/validate_predictions.R#L8

@brookslogan to have this script be more portable, can we move this code back to loading the package directly?

**Comment by nickreich** [comment]
I think my latest commit solves this, but wanted to make sure there wasn't something in a local version of epiforecast that we are missing here.

**Comment by brookslogan** [comment]
Thanks for fixing this.  The load_all statement was staged by mistake; I actually meant only to include library(epiforecast).

Explicitly loading epiforecast should be unnecessary;  it is only used indirectly, as a dependency of one of the other packages loaded.  Maybe there is a missing entry in a DESCRIPTION "Imports:" field somewhere in one of the dependencies, though, because not loading epiforecast raises errors later on.  In any case, the script should work with the current commit.
