### ISSUE TITLE
decide which EW files to include in scoring and weighting calculations

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#41]
Previously, in #14 , we had decided that files from EW40 of year k through EW20 of year k+1 would be submitted. However, @tkcy brought up the point that the challenge does not run for those weeks this year, so we are training on weeks that are not in the competition. A question for @craigjmcgowan : what is the "EW" label for the first and last files that will be submitted for the 2017/2018 season?

**Comment by elray1** [comment]
This is a good point -- it seems like only predictions from the weeks that "would have been scored" in previous seasons if the current scoring rules were used should factor into computing ensemble weights.  On the other hand, a side effect of this would be that we would have more sets of predictions from some years than others; for example, in a region/season with late onset, more weeks of predictions are used for scoring and would therefore enter into training an ensemble for predicting onset timing than in a region/season with an early onset.  That means that region/seasons that last longer would have more weight in determining ensemble weights.  This would probably tend to favor certain types of model over others.  My guess is that from the CDC's perspective, all region/seasons should count equally.  I wonder if it would be reasonable to keep only the weeks that are scored from all seasons, but weight them in the objective function for estimating ensemble weights so that each season contributes equally?  Are weighted means of log scores proper?

**Comment by craigjmcgowan** [comment]
For the 2017/18 season, the forecasts will run from EW43 (submitted Nov 6) to EW18 (submitted May 14). 

For reference, here are the ranges for previous challenges:
2014/15: EW41 to EW19
2015/16: EW42 to EW18
2016/17: EW43 to EW18

As for @elray1's comments, it makes sense to me that we would only want to keep those weeks that contribute to scoring. If that ends up favoring some types of models over others, then it seems to me that those models are the ones that are doing the best at predicting the targets during the time periods when we care the most about having accurate predictions, though I haven't convinced myself of this 100% yet.

**Comment by nickreich** [comment]
Summary of before-dinner debate with @tkcy @elray1 @craigjmcgowan @lepisma @brookslogan :

Option 1) use all submitted weeks, within some bounds.

Option 2) Use all weeks that fell within the "scored zone" of each season based on current rules. This would involve using the current code in `calculate-weights.R` and filtering the scores before passing it to that code.

Option 3) Same as option 2, but with some weighting to adjust for possible biases from longer/shorter seasons.

Decided: we settle on option 2. It is closer to representing an expected log score according to scoring rules. Also, it's easier to implement than option 3.

Following CDC guidelines from 2017/2018 season, using scores from files from each season labeled EW43 through EW18 (i.e. files outside that range will not be considered).
