### ISSUE TITLE
SARIMA2 label not showing up in visualizer

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#68]
![image](https://user-images.githubusercontent.com/1280767/32411386-98730d1e-c1af-11e7-9ff6-b7765d75d978.png)

**Comment by lepisma** [comment]
I believe I know the reason behind this (its up as issue [36](https://github.com/reichlab/d3-foresight/issues/36) on d3-foresight). There are 21 models now and the d3 color scale I used extends upto 20. SARIMA2 is black because the default no color value (`null` or `undefined`) goes as black in svg but in the tooltip its going as transparent (or white).

Will add a custom color scale here, most probably by interpolating the d3's limit.
