### ISSUE TITLE
weirdness in EW51 week-ahead forecasts for Region 1

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#98]
Why are these forecasts so off from what looks like should be the expected trajectory? 

![image](https://user-images.githubusercontent.com/1280767/35422434-b01ecc3a-0216-11e8-80a4-c4c152cb3d07.png)

**Comment by lcbrooks** [comment]
This might be a bug with fetching the appropriate version of the data.  [Our similar visualizer](https://delphi.midas.cs.cmu.edu/forecast/) shows a sharp drop down from EW50 to EW51, which may explain the lower forecasts for EW52--EW3.

**Comment by nickreich** [comment]
Thanks for the investigation, @lcbrooks . So are you suggesting that the bug was in the forecast model's retrieval of the data? These two visualizations are not independent, as the week-ahead forecasts are almost 50% taken from Delphi models. I'm also confused why we only see it in Region 1. Based on the above ensemble visualizer, the lag 0 data available for the EW51 forecast (dark green line) has not been substantially revised since that time (light green line).

**Comment by lcbrooks** [comment]
It does seem to be about data retrieval, comparing with epivis and a similar forecast visualizer [here](https://delphi.midas.cs.cmu.edu/forecast/).  They seem to disagree on what the input data was; I'm not sure if they agree or not on what the latest data is.

The problem is not exactly what I was suggesting before, because the input for the latest forecasts shown (EW2) does not match the lag-0 data from the API, which has a spike down at EW51.

It is very suspicious that as you move left and right through the historical forecasts, that the rightmost dark green point always seems to lie exactly on the light green line.  Maybe this does suggest a problem with lags vs. issues, but maybe the latest data is based on lag-1 rather than lag-0?

**Comment by nickreich** [comment]
@lepisma do you have any thoughts or insight about this problem? You've worked more closely with the data retrieval API than I have.

**Comment by lepisma** [comment]
Fixed now. As @lcbrooks said, the lag 0 value for this specific case was pretty low (~1.4) and was shadowed by latest lag values.

**Comment by nickreich** [comment]
Thanks!
